import { fetchRandomAvatar } from '~/components/root/utils/storage'
import {
  createAutoGeneratedRoom,
  sendCallerOfferToDb,
  sendLocalIceCandidatesToDb,
} from '~/components/screens/home/_components/controls/utils/create'
import { close } from '~/components/screens/home/_components/controls/utils/terminate'
import { setupFirebase } from './firebase'

setupFirebase()

export {
  createAutoGeneratedRoom,
  fetchRandomAvatar,
  sendCallerOfferToDb,
  sendLocalIceCandidatesToDb,
  close as terminate,
}
