import { addDoc, collection, doc, updateDoc } from 'firebase/firestore'
import { useFirestore } from '~/lib/firebase'

async function createAutoGeneratedRoom() {
  const db = useFirestore()
  const doc = await addDoc(collection(db, 'rooms'), {})
  return doc.id
}

function sendLocalIceCandidatesToDb({
  candidate,
  roomID,
  role,
}: {
  // eslint-disable-next-line no-undef
  candidate: RTCIceCandidateInit
  roomID: string
  role: 'caller' | 'callee'
}) {
  const db = useFirestore()
  if (roomID.length > 0) addDoc(collection(db, 'rooms', roomID, `${role}Candidates`), candidate)
}

type SdpOffer_answer = {
  // eslint-disable-next-line no-undef
  type: RTCSdpType
  sdp?: string
}

function sendCallerOfferOrAnswerToDb(
  roomID: string,
  payload: { offer: SdpOffer_answer } | { answer: SdpOffer_answer },
) {
  const db = useFirestore()
  updateDoc(doc(db, 'rooms', roomID), payload)
}

export { createAutoGeneratedRoom, sendLocalIceCandidatesToDb, sendCallerOfferOrAnswerToDb }
