import { addDoc, collection, doc, updateDoc } from 'firebase/firestore'
import { useFirestore } from '~/lib/firebase'

async function createAutoGeneratedRoom() {
  const db = useFirestore()
  const doc = await addDoc(collection(db, 'rooms'), {})
  return doc.id
}

function sendLocalIceCandidatesToDb({ candidate, roomID }: { candidate: RTCIceCandidateInit; roomID: string }) {
  const db = useFirestore()
  if (roomID.length > 0) addDoc(collection(db, 'rooms', roomID, 'callerCandidates'), candidate)
}

function sendCallerOfferToDb(
  roomID: string,
  offer: {
    offer: {
      type: RTCSdpType
      sdp?: string
    }
  },
) {
  const db = useFirestore()
  updateDoc(doc(db, 'rooms', roomID), offer)
}

export { createAutoGeneratedRoom, sendLocalIceCandidatesToDb, sendCallerOfferToDb }
